# Generated by Django 3.1.5 on 2021-02-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='word',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
