# Generated by Django 3.1.5 on 2021-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_algorithm_poemscansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='scansion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
