# Generated by Django 3.1.5 on 2021-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210318_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
    ]
